TEST_VALUE:
  name: 'dev_cookie'
REDIS_CONFIG:
  host: "127.0.0.1"
  port: "6379"
  auth: ""
  db: 1
MYSQL:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "cym19980206"
  database: "rbac_test"
  logging: true
  entities: ["entity/*.js"]
  poolSize: 10
  connectorPackage: 'mysql2'
  autoLoadEntities: true
  synchronize: false